Repository tom-writes-code/rpgle-repl, pull requests merged in 2022-04, with the labels that each got.

#15 Optimise toUpperCase implementation.
  rpgle/REPL_VARS.RPGLEINC
  rpgle/REPL_VARS.SQLRPGLE
Labels: enhancement

#17 Build rule updates for Bob v2.3.3.
  Rules.mk
  rpgle/Rules.mk
Labels: bug

#23 Remove replrefbld
  rpgle/REPL_PSEU.SQLRPGLE
Labels: bug

#27 Save snippets to session user
  rpgle/REPL_PSEU.SQLRPGLE
Labels: bug

#25 Support comma decimal separators
  rpgle/REPL_EVAL.RPGLE
  rpgle/REPL_HLPR.SQLRPGLE
  rpgle/REPL_INS.SQLRPGLE
  rpgle/REPL_VARS.SQLRPGLE
Labels: bug

#30 Allow parameterised timestamps
  rpgle/REPL_VARS.SQLRPGLE
Labels: bug

#31 Hide readme
  .github/README.md
  .github/readme-media/adding-reference-source.png
  .github/readme-media/debug-session.png
  .github/readme-media/declaring-free-and-fixed-variables.png
  .github/readme-media/executing-loops-and-sql-statements.png
  .github/readme-media/fixed-format-ruler.png
  .github/readme-media/long-result.png
  .github/readme-media/repl-in-action.gif
  .github/readme-media/replload-saved-snippet.png
  .github/readme-media/rpgle-repl-details.png
  .github/readme-media/unable-to-compile.png
Labels: documentation
